name: Unit/Integration tests

on:
  pull_request:
    branches:
      - main
      - branch-*
      - tool-*

jobs:
  run:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.2', '7.4']
        wp-versions: ['5.1', '5.2', 'latest']

        include:
        - operating-system: ubuntu-latest
          php-versions: '5.4'
          wp-versions: '5.1'
          dependency-version: prefer-lowest

    services:
        database:
            image: mysql:5.6
            env:
                MYSQL_ROOT_PASSWORD: root
            ports:
                - 3306:3306
            options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5

    name: WP ${{ matrix.wp-versions }} with PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }}.

    env:
      WP_TESTS_DIR: "/tmp/tests/phpunit"
      WP_CORE_DIR: "/tmp/wordpress-develop/"

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        coverage: none
        tools: composer:v1, phpunit, cs2pr
        extensions: mysql

    - name: Setup problem matchers for PHP
      run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"

    - name: Setup problem matchers for PHPUnit
      run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Get composer cache directory
      id: composercache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ${{ steps.composercache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}-${{ matrix.dependency-version }}-
        restore-keys: ${{ runner.os }}-composer-${{ matrix.dependency-version }}-

    - if: ${{ matrix.dependency-version }} == prefer-lowest
      name: Install dependencies with prefer-lowest
      run: |
        composer remove automattic/phpcs-neutron-standard dealerdirect/phpcodesniffer-composer-installer phpcompatibility/phpcompatibility-wp phpmetrics/phpmetrics roave/security-advisories squizlabs/php_codesniffer szepeviktor/phpstan-wordpress wp-coding-standards/wpcs
        composer update --${{ matrix.dependency-version }} --prefer-dist --no-progress --no-suggest --no-interaction

    - if: ${{ matrix.dependency-version }} != prefer-lowest
      name: Install dependencies
      run: composer update --prefer-dist --no-progress --no-suggest --no-interaction

    - name: Install tests
      run: bash bin/install-wp-tests.sh wordpress_test root root 127.0.0.1:3306 ${{ matrix.wp-versions }}

    - name: Run test
      run: composer run-tests
